on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --tags
          git tag
          git fetch --tags https://github.com/microsoft/vscode-js-debug.git
