on:
  push:
  workflow_dispatch:

name: sync-tags

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v3
          
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --tags https://github.com/microsoft/vscode-js-debug.git
          git push --tags
